spring:
  application:
    name: demospringdata
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: brucehan
    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        show_sql: true

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace